[2025-05-28T02:48:49.633+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T02:48:49.653+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dependency_dag.task2 scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T02:48:49.661+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dependency_dag.task2 scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T02:48:49.662+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-28T02:48:49.679+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): task2> on 2025-05-27 00:00:00+00:00
[2025-05-28T02:48:49.694+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-28T02:48:49.699+0000] {standard_task_runner.py:72} INFO - Started process 2226 to run task
[2025-05-28T02:48:49.695+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dependency_dag', 'task2', 'scheduled__2025-05-27T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Sesion2/Ejemplo4.py', '--cfg-path', '/tmp/tmpcvlx3kc3']
[2025-05-28T02:48:49.704+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask task2
[2025-05-28T02:48:49.735+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-28T02:48:49.801+0000] {task_command.py:467} INFO - Running <TaskInstance: dependency_dag.task2 scheduled__2025-05-27T00:00:00+00:00 [running]> on host 31d54648d280
[2025-05-28T02:48:49.805+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-28T02:48:49.973+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dependency_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-27T00:00:00+00:00'
[2025-05-28T02:48:49.977+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T02:48:49.995+0000] {logging_mixin.py:190} INFO - Task 2
[2025-05-28T02:48:49.996+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-28T02:48:50.007+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T02:48:50.007+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dependency_dag, task_id=task2, run_id=scheduled__2025-05-27T00:00:00+00:00, execution_date=20250527T000000, start_date=20250528T024849, end_date=20250528T024850
[2025-05-28T02:48:50.047+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-28T02:48:50.099+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T02:48:50.102+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
