[2025-05-30T01:24:03.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T01:24:03.559+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:28:00+00:00 [queued]>
[2025-05-30T01:24:03.609+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:28:00+00:00 [queued]>
[2025-05-30T01:24:03.610+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T01:24:03.720+0000] {taskinstance.py:2888} INFO - Executing <Task(SqlSensor): check_flag> on 2025-05-29 02:28:00+00:00
[2025-05-30T01:24:03.799+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1381) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-30T01:24:03.812+0000] {standard_task_runner.py:72} INFO - Started process 1391 to run task
[2025-05-30T01:24:03.803+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'flag_check_mysql_dag', 'check_flag', 'scheduled__2025-05-29T02:28:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/Sesion3/Ejemplo7.py', '--cfg-path', '/tmp/tmpaqtl8uk0']
[2025-05-30T01:24:03.819+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask check_flag
[2025-05-30T01:24:03.906+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:24:04.082+0000] {task_command.py:467} INFO - Running <TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:28:00+00:00 [running]> on host 31d54648d280
[2025-05-30T01:24:04.091+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:24:04.788+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flag_check_mysql_dag' AIRFLOW_CTX_TASK_ID='check_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T02:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-29T02:28:00+00:00'
[2025-05-30T01:24:04.796+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T01:24:05.168+0000] {base.py:84} INFO - Retrieving connection 'my_db_connection_mysql'
[2025-05-30T01:24:05.176+0000] {sql.py:96} INFO - Poking: SELECT flag FROM my_table WHERE id = 1 (with parameters None)
[2025-05-30T01:24:05.217+0000] {base.py:84} INFO - Retrieving connection 'my_db_connection_mysql'
[2025-05-30T01:24:05.280+0000] {sql.py:509} INFO - Running statement: SELECT flag FROM my_table WHERE id = 1, parameters: None
[2025-05-30T01:24:05.281+0000] {sql.py:518} INFO - Rows affected: 1
[2025-05-30T01:24:05.283+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-05-30T01:24:05.314+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T01:24:05.314+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=flag_check_mysql_dag, task_id=check_flag, run_id=scheduled__2025-05-29T02:28:00+00:00, execution_date=20250529T022800, start_date=20250530T012403, end_date=20250530T012405
[2025-05-30T01:24:05.742+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-30T01:24:06.034+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-30T01:24:06.048+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
